### ISSUE TITLE
Mimic Heroku cli parameters to run > 1 process per app

### ISSUE THREAD

**Issue by saidimu** [sehrope/dokku-logging-supervisord#1]
Heroku's command-line `heroku` supports [concurrency](https://devcenter.heroku.com/articles/scaling#scaling) this way:

```
heroku ps:scale web=2 worker=3
   Scaling web processes... done, now running 2
   Scaling worker processes... done, now running 3
```

How feasible is it to implement a slightly modified parameter for this plugin?

Something along the lines of:

```
dokku:supervisord scale web=2 worker=3
   Scaling web processes... done, now running 2
   Scaling worker processes... done, now running 3
```

Could this be achieved by using by incrementing/decremnting the [`numprocs`](http://supervisord.org/configuration.html#program-x-section-settings) setting in `supervisord.conf` and then reloading the configuration file by sending a [`SIGHUP`](http://supervisord.org/running.html#signals) signal to the `supervisord` process?

**Comment by kelvin22** [comment]
Sorry to comment on an old issue...

How exactly do you go about using SO_REUSEPORT?

**Comment by sehrope** [comment]
> How exactly do you go about using SO_REUSEPORT?

It's a socket option when you're creating a server socket that listens on a port. The specifics of how to configure it will depend on your programming language. Your best bet is to do a search for it plus your language/framework for a working example.

**Comment by kelvin22** [comment]
So on a nginx (dokku's), gunicorn, flask, Python stack, would it be handled
by gunicorn? Seems like each of those supports it in some form.

**Comment by sehrope** [comment]
You wouldn't have to touch nginx. I think it also supports that option but it's outside the scope of what I'm describing here.

Using the option within a dokku app is to allow for separate web processes to listen on the same port. That way when nginx forwards a web request to your app, it can be processed by any one of the processes. Without the SO_REUSEPORT option, whichever web process binds to the port first will "win" and the rest will be rejected from listening on it as it's already in use.

Note that it's probably simpler to use a web stack that handles this internally without SO_REUSEPORT and stick to web=1. For example gunicorn supports forking multiple processes and will automatically handle them listening on the same port.

**Comment by kelvin22** [comment]
Thanks @sehrope, your comments gave me the direction I needed to research. There isn't always much information on how all the components of the web stack interact. I've now got a deeper understanding, and have taken on board your suggested gunicorn method of handling multiple processes.
