### ISSUE TITLE
Problem After try to config:set something

### ISSUE THREAD

**Issue by chayutzee** [sehrope/dokku-logging-supervisord#24]
When i try to config:set some key then my dokku Application deployed:
I got this error in my web.00.log file 
Errno 2] No such file or directory: '/app/static/CACHE/css/872fa5081801.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/c6e8c66a889f.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/758c32c09d4e.css'
[Errno 2] No such file or directory: '/app/static/CACHE/js/daabd9e2de7a.js'
[Errno 2] No such file or directory: '/app/static/CACHE/css/872fa5081801.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/872fa5081801.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/c6e8c66a889f.css'
[Errno 2] No such file or directory: '/app/static/CACHE/js/daabd9e2de7a.js'
[Errno 2] No such file or directory: '/app/static/CACHE/css/758c32c09d4e.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/c6e8c66a889f.css'
[Errno 2] No such file or directory: '/app/static/CACHE/js/daabd9e2de7a.js'
[Errno 2] No such file or directory: '/app/static/CACHE/css/758c32c09d4e.css'
[Errno 2] No such file or directory: '/app/static/CACHE/css/872fa5081801.css'

all my static file gone but if i just push again from my desktop it will work fine ! 

Is this dokku-logging-supervisord bug ?​

**Comment by sehrope** [comment]
This looks like an app bug and not plugin related. If you can recreate it on the latest version of the plugin/dokku please reopen the issue.
