### ISSUE TITLE
Cannot define custom stdout/stderr output

### ISSUE THREAD

**Issue by thepuzzlemaster** [sehrope/dokku-logging-supervisord#25]
I'm having an issue getting a custom output to work.

My package.json has the following start script:

````
"start": "npm run server & npm run batch-deploy",

"server": "node server/server.js >> /var/log/dokku/studio-sensors/node.log 2>> /var/log/dokku/studio-sensors/node.err",
"batch-deploy": "node server/batch-deploy.js >> /var/log/dokku/studio-sensors/batch-deploy.log 2>> /var/log/dokku/studio-sensors/batch-deploy.err"
````

I would have thought that since /var/log/dokku/studio-sensors is being mounted as a volume, it would be accessible inside the container, however, I'm getting the following error when running:

````
sh: 1:
cannot create /var/log/dokku/studio-sensors/node.log: Directory nonexistent
````

Am I doing something wrong, or is this not possible?

Alternatively, is there another way to get the 2 processes to output to independent files? Less concerned with stderr and stdout being separate, as much as having the server task and batch-deploy task have separate output.

**Comment by michaelshobbs** [comment]
I believe the aforementioned directory is actually mounted as `/var/log/app` inside the container.

**Comment by michaelshobbs** [comment]
See here: https://github.com/sehrope/dokku-logging-supervisord/blob/master/docker-args

**Comment by thepuzzlemaster** [comment]
Cool thanks. Let me give that a try! I forgot that it might be mounted with a different name.

**Comment by thepuzzlemaster** [comment]
Awesome. Yup that was totally it! Thanks for the quick reply!
