### ISSUE TITLE
Scale filename should be the same as Dokku uses

### ISSUE THREAD

**Issue by srigi** [sehrope/dokku-logging-supervisord#29]
In [this Dokku issue](https://github.com/progrium/dokku/issues/1409) and [in sources of Dokku](https://github.com/progrium/dokku/blob/51e8b540cc7f347d350608ded05a4cedef6ec8d8/dokku#L69) you can see that `SCALE` file was renamed to `DOKKU_SCALE`. This project should follow and use the same name.

**Comment by michaelshobbs** [comment]
As this plugin and dokku core handle scaling in very different ways, I think it makes sense to not have their configuration filenames overlap.

**Comment by srigi** [comment]
Ah OK, I was thinking this plugins is replacing default Dokku scale mechanism.
