### ISSUE TITLE
Does this break zero downtime deploys?

### ISSUE THREAD

**Issue by jorisw** [sehrope/dokku-logging-supervisord#39]
My `Procfile` looks like this:

```
web: node -r babel-register -r babel-polyfill src/web/index.js
mailer: node -r babel-register -r babel-polyfill src/mailer/index.js
```

When I push a new release or do a `dokku ps:rebuild`, right after it switches containers and reloads nginx, for a while (more than a minute) I see a page that says:

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

Googling for this phrase, apparently it's dokku's internal 500 error file for nginx:
https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/500-error.html

So, does this plugin break zero downtime deployment?

**Comment by sehrope** [comment]
This plugin out of date, has not been updated in quite a while, and should be avoided. It was written in the early days of Dokku before similar features were included in core. At the time Dokku only supported a single process type (web).

It shouldn't be necessary anymore either as Dokku now has out of the box support for multiple process types, scaling out web/workers, and centralized logging. Those features should also play nicely with the built in zero downtime deploys.

I'd suggest using the out of the box support for these in a new version of Dokku.

**Comment by jorisw** [comment]
May wanna put that in your `README.md` ?

**Comment by jorisw** [comment]
FWIW other than breaking zero downtime deploys, it does its job centralizing the logging.

**Comment by sehrope** [comment]
> May wanna put that in your README.md ?

It says, "*Deprecated as of ...*" on the README but probably should make it more prominent. Thanks for the suggestion.

> FWIW other than breaking zero downtime deploys, it does its job centralizing the logging.

That's pretty cool that the logging centralization still works. I haven't tested the plugin on recent versions of Dokku so wasn't sure.

FYI, with a modern docker install there would be a lot more / better options for this. Should be just some global docker config to route the logs elsewhere: https://docs.docker.com/engine/admin/logging/overview/

**Comment by jorisw** [comment]
Thanks. I'm using Dokku 0.10.5, latest at present, but can't find the centralized logging system. Were you referring to the event logger? I'm trying to get `console.log()` entries in something like `/var/log/dokku/appname.log` on the host system.

**Comment by sehrope** [comment]
I'm not sure but I would imagine it would defer to Docker with per-container logs.

Try asking on IRC / Slack or on the main Dokku repo.
