### ISSUE TITLE
You cannot attach to a stopped container, start it first

### ISSUE THREAD

**Issue by michaelshobbs** [sehrope/dokku-logging-supervisord#5]
We're seeing the aforementioned error occasionally when pushing our nodejs app. I think its in the dokku-logging-supervisord plugin as we never get past the "Releasing app" output from dokku and the last command to run is /bin/bash -c cat > '/build/procfile-to-supervisord'. In fact it's most likely happening on line 14 of lib/helpers. Do we need to attach there?

We are on the latest master of dokku-logging-supervisord and dokku.

---- Begin output of git push dokku@localhost:myapp.mydomain.com master ----
STDOUT:
-----> Cleaning up ...
-----> Building myapp.mydomain.com ...
remote: HEAD is now at b1c4df7... logo experiment
-----> Checking Hostkeys Plugin sanity ...
-----> Installing Hostkeys in build environment ...
       No app keys available.
       Adding shared keys.
-----> Done Installing Hostkeys in build environment ...
       Added the following keys:
       |1|M8rxTmTXpFjumpcmYqL3OXTDhDo=|ywAg1+aPQJSUvknRY0KM3VRjrlg= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
       Node.js app detected
-----> Requested node range:  0.10.25
-----> Resolved node version: 0.10.25
-----> Downloading and installing node
-----> Restoring node_modules directory from cache
-----> Pruning cached dependencies not specified in package.json
-----> Writing a custom .npmrc to circumvent npm bugs
-----> Installing dependencies
       npm WARN package.json expa@0.0.0 No repository field.
       npm WARN package.json express-session@1.0.2 No repository field.
       npm WARN package.json juice@0.4.0 No repository field.
       npm WARN package.json uid2@0.0.3 No repository field.
       npm WARN package.json wiggin@0.4.0 No repository field.
       npm http GET https://registry.npmjs.org/expa
       npm http 404 https://registry.npmjs.org/expa
-----> Caching node_modules directory for future builds
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing myapp.mydomain.com ...
remote: 2014/04/09 04:16:57 You cannot attach to a stopped container, start it first
To dokku@localhost:myapp.mydomain.com
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@localhost:myapp.mydomain.com'
---- End output of git push dokku@localhost:myapp.mydomain.com master ----
Ran git push dokku@localhost:myapp.mydomain.com master returned 1

**Comment by srigi** [comment]
I'm getting this error for one of my PHP applications. The other one deploys without issues.
Abovementioned tips doesn't apply anymore, `docker attach` is not in the code.

I recorded failed deploy with [trace](http://pastebin.com/ixxcTxvh).
